
document.write("<FONT face='arial' size='2'><b>")
document.write("<font size='5' color='navy'>Il Calendario<br>della Terra</font><br><br><br><br>")
document.write("<font color='red'>IL LIBRO</font><br><br>")
document.write("<A class='ebook' HREF='text.htm' target='internal_frame'>Frontespizio</a><br><br>")
document.write("<A class='ebook' HREF='introduzione.htm' target='internal_frame'>Introduzione</a><br><br>")
document.write("<A class='ebook' HREF='annozero.htm' target='internal_frame'>Anno zero</a><br>")
document.write("<A class='ebook' HREF='eagle.htm' target='internal_frame'>“... The Eagle has landed.”</a><br>")
document.write("<A class='ebook' HREF='login.htm' target='internal_frame'>“ Log - in ”</a><br>")
document.write("<A class='ebook' HREF='nuovi_giorni.htm' target='internal_frame'>Nuovi giorni per nuovi esseri umani</a><br>")
document.write("<A class='ebook' HREF='settimana.htm' target='internal_frame'>Lo schema settimanale</a><br>")
document.write("<A class='ebook' HREF='poteri.htm' target='internal_frame'>I poteri dell’animo</a><br>")
document.write("<A class='ebook' HREF='celebrazioni.htm' target='internal_frame'>Celebrazioni universali</a><br>")
document.write("<A class='ebook' HREF='inizio_fine.htm' target='internal_frame'>Inizio e fine d’anno</a><br>")
document.write("<A class='ebook' HREF='equsol.htm' target='internal_frame'>Equinozi e Solstizi</a><br>")
document.write("<A class='ebook' HREF='rotta.htm' target='internal_frame'>Tieni la giusta rotta!</a><br>")
document.write("<A class='ebook' HREF='interpretazioni.htm' target='internal_frame'>Alcune interpretazioni morali</a><br>")
document.write("<A class='ebook' HREF='mesi.htm' target='internal_frame'>Numerazione dei mesi</a><br>")
document.write("<A class='ebook' HREF='settenni.htm' target='internal_frame'>I settenni</a><br>")
document.write("<A class='ebook' HREF='globalismo.htm' target='internal_frame'>Globalismo e calendario</a><br><br>")
document.write("<A class='ebook' HREF='note.htm' target='internal_frame'>Note</a><br>")
document.write("<A class='ebook' HREF='appendice.htm' target='internal_frame'>Appendice tecnica</a><br><br><br><br>")
document.write("<font color='red'><b>ALMANACCO<br>del corrente anno. I mesi:</b></font><br><br>")
document.write("<table cellspacing='7'><tr><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='1_it.htm' target='internal_frame' title='Primo mese'>1</a></td><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='2_it.htm' target='internal_frame' title='Secondo mese'>2</a></td><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='3_it.htm' target='internal_frame' title='Terzo mese'>3</a></td><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='4_it.htm' target='internal_frame' title='Quarto mese'>4</a></td><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='5_it.htm' target='internal_frame' title='Quinto mese'>5</a></td><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='6_it.htm' target='internal_frame' title='Sesto mese'>6</a></td></tr><tr><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='7_it.htm' target='internal_frame' title='Settimo mese'>7</a></td><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='8_it.htm' target='internal_frame' title='Ottavo mese'>8</a></td><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='9_it.htm' target='internal_frame' title='Nono mese'>9</a></td><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='10_it.htm' target='internal_frame' title='Decimo mese'>10</a></td><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='11_it.htm' target='internal_frame' title='Undicesimo mese'>11</a></td><td width='16%' align='center'>")
document.write("<A class='ebook_months' HREF='12_it.htm' target='internal_frame' title='Dodicesimo mese'>12</a></td></tr></table>")
document.write("</b></FONT>")
